name: Android CI/CD

on:
  push:
    tags:
      - 'v*'

jobs:
  workflow-lint:
      uses: ./.github/workflows/runner-app-lint.yaml

#  workflow-unit-test:
#      needs: [ workflow-lint ]
#      uses: ./.github/workflows/runner-app-test-unit.yaml
#
#  workflow-android-test:
#      needs: [ workflow-unit-test ]
#      uses: ./.github/workflows/runner-app-test-android.yaml
#
  workflow-publish:
#    needs: [ workflow-lint, workflow-unit-test,workflow-android-test ]
    needs: [ workflow-lint ]
    uses: ./.github/workflows/runner-app-publish-apk.yaml
    secrets:
      SIGNING_KEY_BASE_64: "MIIJ0AIBAzCCCXoGCSqGSIb3DQEHAaCCCWsEgglnMIIJYzCCBaoGCSqGSIb3DQEHAaCCBZsEggWX
MIIFkzCCBY8GCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUM
MCsEFL2sT8Nm45TBkRhwcQfP+FyFr1EMAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQB
KgQQoxR5np0PDQjEtJ0b2cuD9QSCBNCCGMo+qo4INUVaSvy0V4OBMHfiBFP8EOLYpmHuwvG5TusG
MPJTawX1P9FREmoWQI5M1nwNPJsDihP19N4Tfcxk/zpmvq6NoXVz98dgJL+MCkgST44peMANSiXv
W2z3a0ee2nINET1gT5IOKVM8etif7yKG1sJiVEuTcQgqVaMrf1C2B2y4pgZuBKu4/jXZe2X4EzcH
9aL6GmjtzUnGnfREvzejp28Rt12UGjGOoSaUzlaAEdgblvhXVN6wIgsqyK6xtndcNNkTC2LqOep1
28w0uwzGC87RKYZDxyz+brXYIhYp1KVF1Eo11F4hy9IV9HkY4GjwMB4hPo1+AQMPgJ831KSvW+TX
HQ9DhM9yI+2uZdxPR/Lj1Fhjo/L8MTzD7F63rCHL3t/Yl4hWkhy03sb6mU6Gcysgyg4dhRCRFHHC
jJUdXVl7hSe7MzNLCHWHObenO7b1Pt83pMOhJmjCuVFCBxH6OMUTwPZLFJYKoKo1ECVsdNGBsX4j
WZCt2xwHJE4C7KZL5dvfjLY8rvcRnqbZUdJejJSKY4krmH7zESWnkjOnVlnc6TPvHRxO7h4kA7Of
5xUHzfu5SI9qQtRrELfQ+dqVxCIMMmeIa1S9yuCKIV8FDS/BjHF0Ox5gRvSHMcn+8GmlP/t5Jy94
zAY8BpoHDaFUji0T5JPi6ALyC3XF0s8/kTRMyVD0eGRYn9uI+IEFPalBB7Nwf+jNQvdqvhmMgfCQ
Yo7A/SST34Vrl4dErBW+em8VKQk80xtzQR+nyh18NWmv6tI4HYu13sDnC4R5ABMDPlyPI8ki/pHa
jsXz22mxxb4k1ua0polyeFqP6Xb71o31Vt8G4ZAqobdMHbVxwQtI5wrnRat1sLq9uKYEUyRZ+BA/
Ro35Z0PcIgzJZqZd7ZfEFa8eJdddF/5b0xAIw9N2ise6UG/1ZaGhZUOs6tXlDKpqahk/PiQXdbuJ
R7y6qET7u+KtrxAVEMDYifiVh95A13n72z2FFkiKpujJmS88zF4CqQJSobe4NRYAXep3kqIqqMtF
pRjVMRNsgMu5xXDaTz3U9ddVcCK8mxi31lSYjJnClC36fJp0N/B6AuJzGVvD8wnRGa2P2frDisaF
pONmXAPrEBMUoxZFqdE3MwRgbisxjcs7CQ45aYyV1EtvhgW4kTPReZAuxiLVSU+X4qmaHQtOU3UV
6SZWCK4AV+kt+vetgw5ZHMo9bFeOOZBp0RD/rJBx6hNN8lEB6pxmmDA0aMfz2IbwCYAFB9k7FqSR
+l577YKS/LpAcljRiGN1I8hIs6O1f/HswvIIMYdaItJzWx4eNx30izlPOrEfbCJxZJMsffJwdCn1
X2lH4VdDRJdhamnmL5RtsoO87QkpQeZi8JdjYWHHuu93wu01m7SKoNxXxo/jqD++YNpENTo4WWu+
LOnvQYZ1BL2u4qsAlg3c8gdq7JbbJFrl1C2hZbT4sfHaya2ef1huvqIsk+fcAF9JQAEdqB7rQI7M
rEEVMZan/oRcwqsMOmjuzVdwtbxuuiwdKmR45rKtkb8K+OxqASZJ5OuWkXqTeIFRU8MHAUKeaK4t
W7LhCH3mLtMk8kC2w/RSrUasX3BHyheYayxlrD2AETI/kB5V1JWgQhfKFoek6R1SfU2SoEGTa8BX
hjE8MBcGCSqGSIb3DQEJFDEKHggAawBlAHkAMDAhBgkqhkiG9w0BCRUxFAQSVGltZSAxNjgzMDk2
NTMwOTMxMIIDsQYJKoZIhvcNAQcGoIIDojCCA54CAQAwggOXBgkqhkiG9w0BBwEwZgYJKoZIhvcN
AQUNMFkwOAYJKoZIhvcNAQUMMCsEFPKuOPA0P00s09KWx5Kjq4M3hJ5lAgInEAIBIDAMBggqhkiG
9w0CCQUAMB0GCWCGSAFlAwQBKgQQOduxp/OJFyox1n0nW+j/j4CCAyDAAJgO3hSFnI4EnKpu5gtD
YOXVDKhle18cnr0tdF7ktiIrmx8c15x4+p28Bur5R6s02lr97wNXycTuHwWFo5peMtGgWqK5VU+u
tem71YqSWlvzDu6InRoExHPRaAWC01kpFWZVK7mURrkFQKqaxOTV+qlhOkRw5/fwKx+Na4rtrVVY
DVd8a7WoMrJZVxrxHGNTodoWoS8Bul7jgUsYRfMN/G50EOzf319JjKX2GC0Cw04cVAxkVNd1PDCe
HbbiUj6uV8Xhvj/zspJXd704qM1ALl0hKER1FGcOzt3c0A5Xxai1kKxo4Y5E62zItNhOkhlwVnem
bYF58z5C8y2gEzb20ZmJtkhoHgipkzkfND1oU7e//jSnR/hoGAjKKPRMMusqcKKeIyg3YTp+h/bc
TfmN6C2LgjoHSq1w6uM8E8KwpmqkZbA/O97rUh3uHM9RZZS0XGtCORCP/9LJT7am/M5QxWYHtlUN
JkwX49qA0o82AGNmYJhOFkaLSScww12fjACEyKViO6PQ/aM1GBgtvnLDjYAjYacX3epyn/vD1tuI
dBp4uscSi2GusrslQLWyjpBp//SaouKgFHIVVYxDJqqR1A47ndhKzsq+zX0LryX0S+1mFhsi3c5R
8+4epSfdf/RicDpa+uV6vrfBq27s3FyyafXgXmY43Pet1qr/ksvpQnSpnheDRCP5yCcl1mjgmSmi
KlmOZbTn7QSHoWlMEAKJorXcdC6EIk5doCgdTzAdFaN2jRiBar0kt/6GgT7lPmkx5cTRvt/JGIqa
NnZv9bgmdfxgJHC2J0HuvvB/lLFqBxpUUAIkBTKyd298MSGLyvy+h85Y44G/YnWhoUFyfqWpvBTY
+W4++oHyzCzL0UhDW5BK4JUlnzphWdSZAqqVRzffLwZOMe1KyLJ2C392BsqyBdZmHqHU+1sfZBwd
/2CLg78jSj4xVjU5xoEPHPnZ70bc+daZbMAIuvGXI8M+GFQGHPya+2kD8NuYl2/QltD8x6V1y0NU
UO1/JybEc9wX04K/xJcBXa2FwH9dAPzn239WONl26xblcmSaIAStx+3xwjBNMDEwDQYJYIZIAWUD
BAIBBQAEIK5LjcRpHVs1NffGFtHspbWu4VW+bwDnNspn2i+8MwnxBBSAVFouXCQo1tvHoWLYI1rx
2AwlcwICJxA=
"
      KEY_ALIAS: "key0"
      STORE_PASSWORD: "123456789"
      KEY_PASSWORD: "key123456"
##