name: Android CI/CD

on:
  push:
    tags:
      - 'v*'

jobs:
  workflow-lint:
      uses: ./.github/workflows/runner-app-lint.yaml

#  workflow-unit-test:
#      needs: [ workflow-lint ]
#      uses: ./.github/workflows/runner-app-test-unit.yaml
#
#  workflow-android-test:
#      needs: [ workflow-unit-test ]
#      uses: ./.github/workflows/runner-app-test-android.yaml
#
  workflow-publish:
#    needs: [ workflow-lint, workflow-unit-test,workflow-android-test ]
    needs: [ workflow-lint ]
    uses: ./.github/workflows/runner-app-publish-apk.yaml
    secrets:
      SIGNING_KEY_BASE_64: "BASE64_ENCODED_SIGNING_KEY"
      KEY_ALIAS: "key0"
      STORE_PASSWORD: "123456789"
      KEY_PASSWORD: "key123456"
##