name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install @actions/github

      - name: Download APK asset from latest release
        id: download-apk
        uses: actions/download-artifact
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: runner-app-publish-apk.yaml # the workflow file name where the artifact was created
          name: app-release-signed # the name of the artifact you want to download
          path: app/

#      - name: Download APK from Release
#        uses: actions/github@v1.0.0
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          repository: gamalragab21/CI-CDexample
#          path: app-release-signed.apk
#          ref: refs/tags/$(git describe --abbrev=0 --tags)

#      - name: Save APK to directory
#        run: mv app-release-signed.apk apk/

#      - name: Download APK from Release
#        uses: actions/download-artifact@v2
#        with:
#          name: app-release-signed
#          path: app/
#          url: https://api.github.com/repos/gamalragab21/CI-CDexample/releases/latest
#          token: ${{ secrets.GITHUB_TOKEN }}

      #      - name: Download APK from GitHub release
      #        uses: actions/download-artifact@v2
      #        with:
      #          name: app-release-signed
      ##          path: app/
      #          ref: ${{ github.event.release.tag_name }}

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          #          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: qa
          file: app/app-release-signed.apk

#      - name: Install and configure Firebase CLI
#        uses: firebase/firebase-cli@v1.2.0
#        with:
#          args: 'deploy --only hosting'
#        env:
#          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

#      - name: Upload APK to Firebase App Distribution
#        uses: firebase/app-distribution-upload@v1
#        with:
#          appId: ${{ secrets.FIREBASE_APP_ID }}
#          token: ${{ secrets.FIREBASE_TOKEN }}
#          apkPath: app/app-release-signed.apk
#          releaseNotesFile: app/release_notes.txt