name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from GitHub release
        uses: actions/download-artifact@v2
        with:
          name: app-release-signed
          path: app/
          ref: ${{ github.event.release.tag_name }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install and configure Firebase CLI
        uses: firebase/firebase-cli@v1.2.0
        with:
          args: 'deploy --only hosting'
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Upload APK to Firebase App Distribution
        uses: firebase/app-distribution-upload@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          apkPath: app/app-release-signed.apk
          releaseNotesFile: app/release_notes.txt