#name: FinPay-v2 Release
#on:
#  push:
#    tags:
#      - 'v*'
#
#jobs:
#  start:
#    name: Start Deploy Workflow
#    runs-on: ubuntu-latest
#    steps:
#      - name: Ping Slack Test & Deploy Android APK Started
#        uses: someimportantcompany/github-actions-slack-message@v1
#        with:
#          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
#          text: Test & Deploy APK Started
#
#  workflow-lint:
#    uses: ./.github/workflows/runner-app-lint.yaml
#    secrets:
#      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#
#  workflow-unit-test:
#    needs: [ workflow-lint ]
#    uses: ./.github/workflows/runner-app-test-unit.yaml
#    secrets:
#      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#
#  workflow-publish:
#    needs: [ workflow-lint, workflow-unit-test ]
#    uses: ./.github/workflows/runner-app-publish-apk.yaml
#    secrets:
#      SIGNING_KEY_BASE_64: ${{ secrets.SIGNING_KEY_BASE_64 }}
#      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
#      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
#      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
#      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#
#  finish:
#    needs: [ workflow-publish ]
#    name: Finish Deploy Workflow
#    runs-on: ubuntu-latest
#    steps:
#      - name: Ping Slack Test & Deploy APK Finished Successfully
#        uses: someimportantcompany/github-actions-slack-message@v1
#        if: success()
#        with:
#          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
#          text: |
#            *A New release APK Uploaded Successfully*
#            ${{ needs.workflow-publish.outputs.release_url }}
#          color: success
#
#      - name: Ping QA Test & Deploy APK Finished Successfully
#        uses: someimportantcompany/github-actions-slack-message@v1
#        if: success()
#        with:
#          webhook-url: ${{ secrets.SLACK_WEBHOOK_QA }}
#          text: |
#            *A New release APK Uploaded Successfully*
#            ${{ needs.workflow-publish.outputs.release_url }}
#          color: success
#
#      - name: Ping Slack Test & Deploy Android APK Failed
#        uses: someimportantcompany/github-actions-slack-message@v1
#        if: failure()
#        with:
#          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
#          text: |
#            *A new Release failed*
#          color: failure
