name: Run Instrumentation-test
on:
  workflow_call:

jobs:
  instrumentation-test:
    name: Run Instrumentation test
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'


      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Upload instrumentation test report
        # Upload report to ubuntu server to be used on another action...
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: instrumentation_test_report
          # module path.....
          path: '**/build/reports/androidTests/connected/'

#      - name: Ping Slack Instrumentation-test Failed
#        uses: someimportantcompany/github-actions-slack-message@v1
#        if: failure()
#        with:
#          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
#          text: |
#            *Instrumentation-test failed*
#          color: failure
